version: '3.9'

services:
  php-proxy:
    build:
      dockerfile: ./docker/php-proxy/Dockerfile
      context: ../
    ports:
      - '8080:8080'
    networks:
      - workforce-management

  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: ../
    ports:
      - "9000:9000"
    networks:
      - workforce-management

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - workforce-management
    volumes:
      - db:/var/lib/postgresql/data

networks:
  workforce-management:
      external: true

volumes:
  db:
    driver: local
